#!/bin/bash

if [ "$1" = "-h" ]; then 
echo "usage: makedist [option]"
echo "Option -m forces generating the mappings"
exit 0
fi

mapcount=`ls mappings/*.tec 2> /dev/null | wc -w`

if [ "$1" = "-m" -o ! -d mappings -o $mapcount = 0 ]; then
perl makemaps.pl
fi

distdir="dist"
pkgdir=$distdir/arabxetex
mapsdir="$pkgdir/fontmapping/"
docdir="$pkgdir/doc/"
srcdir="$pkgdir/source/"
#texdir="$pkgdir/xelatex/"
tdsmapsdir="tds/fonts/misc/xetex/fontmapping/arabxetex/"
tdsdocdir="tds/doc/xelatex/arabxetex/"
tdssrcdir="tds/source/xelatex/arabxetex/"
tdstexdir="tds/tex/xelatex/arabxetex/"

mkdir -p $tdsmapsdir
mkdir -p $tdsdocdir/examples
mkdir -p $tdssrcdir
mkdir -p $tdstexdir
mkdir -p $mapsdir
mkdir -p $srcdir
mkdir -p $pkgdir/examples
#mkdir -p $texdir

cp mappings/*.{map,tec} $mapsdir
mv mappings/*.{map,tec} $tdsmapsdir
rm -rf mappings/

xelatex arabxetex.dtx
xelatex arabxetex.dtx
xelatex arabxetex.dtx

cp *-trans*.map $srcdir 
cp *.maps $srcdir
cp makemaps.pl $srcdir
cp arabxetex.pdf $pkgdir/
cp arabxetex.dtx $pkgdir/
cp ednotes_example.{tex,pdf} $pkgdir/examples
cp minimal.{tex,pdf} $pkgdir/examples
#cp arabxetex.sty $texdir
cp README.md $pkgdir/

cp *-trans*.map $tdssrcdir 
cp *.maps $tdssrcdir
cp makemaps.pl $tdssrcdir
cp arabxetex.pdf $tdsdocdir
cp arabxetex.dtx $tdssrcdir
cp ednotes_example.{tex,pdf} $tdsdocdir/examples
cp minimal.tex $tdsdocdir/examples
cp arabxetex.sty $tdstexdir || exit 1
cp README.md $tdsdocdir

[ -f arabxetex.zip ] && mv arabxetex.zip arabxetex.zip.bak
cd tds
zip -r arabxetex.tds.zip *
mv arabxetex.tds.zip ../dist
cd ..
rm -fr tds/
cd dist
zip -r arabxetex.zip *
mv arabxetex.zip ../
cd ..
#zip arabxetex.zip arabxetex.tds.zip
rm -fr dist/

echo "arabxetex.zip can be uploaded on CTAN..."

echo "Install to ~/texmf/ ? [y/N]"
read -en 1 INSTALL_Q
if [ "$INSTALL_Q" = "y" ] || [ "$INSTALL_Q" = "Y" ]; then
  TEXMFHOME="$HOME/Library/texmf"
  unzip -uo arabxetex.tds.zip -d $TEXMFHOME/ 
  mktexlsr $TEXMFHOME
  echo "update completed"
fi
#rm arabxetex.tds.zip
rm arabxetex*.{aux,glo,idx,ins,log,out,sty,toc}
rm README.tex
